language: node_js
node_js:
  - '4'
sudo: false
after_success:
  - npm run report-coverage
deploy:
  skip_cleanup: true
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: eab1......55dd
    secure: kxmR/wXaAHWgZLlLffAsKzcAYrF+DA/gcDUu1585TGrsNKCSHMHHM/ZpIdF35R6lSDQ1rG9h1Brz29WG/O7Wl9hA+FItO+L/THGKyrPo/6SiX5I/h8WGtCe6p9zSByUGAqL8QCN+BxRmcEecI4SUil6gnQslmFeALbVBqWYmOr3hjQEXq/hkjCxa4Hqyu1silHsYxpLj4ophYHsOdao4MJlHeQY9qQSju5LTGIFSoWkdmedLwvrv8cJmxcG3ddtauoxSGVHpmgdBhYq/pc8FBtKIbxQKRgs5c5uX8PEjbIbKQGdKaIPBeYV8xXqnV/zqZsyXhkO/Y4s4Xm4n95JbqyFe6kipnhQI4BxVRzlkdjy0hhOJlESk4KD/bd9xcsGl97604CZfPqUztHURrJrR99fuLPbC+IIKSySJrzjvNfpsflkXXh/n5d6Mc6AXnCbWDBEmrXO5wCh1lnL9THSXRt2B3VDLSNm+76SIVfQlnafnrZpVgGAKOt5rLKbShk4OPp0XT9feavZC5pjm/ebvQaNtarIQJXKDOZsmNBYWc3mRbiR0AZpydTElTmSP4h59vzA2Jk97lU7cNqF9jZXnV+ulec3YhCfwwY1uYssVVcoP4wWxJnfk0wbyMoYI259c2nUaslWndZCeQZXXmpvDcSOCV1oB5r+Ii0IOSKcmgC4=
  on:
    tags: true
    branch: master
